version: "3"
services:
  redis:
    build: ./containers/redis
    container_name: service-evaluate-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6379:6379"
  app:
    build: .
    container_name: service-evaluate-app
    command: sh -c "dockerize -wait tcp://redis:6379 npm run start:prod"
    depends_on:
      - redis
    environment:
      APPHOST: ${APPHOST}
      APPPORT: ${APPPORT}
      DBHOST: ${DBHOST}
      DBPORT: ${DBPORT}
      DBUSERNAME: ${DBUSERNAME}
      DBPASSWORD: ${DBPASSWORD}
      DBDATABASE: ${DBDATABASE}
      DBSCHEMA: ${DBSCHEMA}
      DBRATETABLE: ${DBRATETABLE}
      REDISRATELIMITURL: redis://127.0.0.1:6379
    ports:
      - 7070:7070